/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jeasy.rules;

public class App {

    public static void main(String[] args) throws Exception {
//        new MvelDemo().runDemo();
//        new JexlDemo().runDemo();
        new DynamicDemo().runDemo();
    }

}
